apiVersion: v1
kind: Service
metadata:
  name: monpfe-mysql
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: monpfe-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
