apiVersion: apps/v1
kind: Deployment
metadata:
  name: monpfe-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monpfe-mysql
  template:
    metadata:
      labels:
        app: monpfe-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "employee_management"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: monpfe-secrets
                  key: db-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: monpfe-secrets
                  key: db-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: monpfe-secrets
                  key: db-password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}
